include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # 自定义规则
    prefer_relative_imports: false
    avoid_print: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - 'build/**'
    - 'lib/generated/**'

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
