name: zjs_flutter_template
description: 'A comprehensive Flutter template with best practices'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理 - Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 路由导航 - GoRouter
  go_router: ^16.2.0

  # 网络请求 - Dio
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # 本地存储
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4

  # UI组件和工具
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.1

  # 工具类
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0

  # 日志和监控
  logger: ^2.6.1
  talker_flutter: ^4.9.3
  flutter_screenutil: ^5.9.3

  # 依赖注入 - GetIt
  get_it: ^8.2.0
  injectable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.5.4
  # hive_generator: ^2.0.1 # 暂时注释掉以解决依赖冲突
  riverpod_generator: ^2.6.5
  freezed: ^3.1.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.9.5

  # 代码检查和格式化
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

  # 测试相关
  mockito: ^5.4.4
  mocktail: ^1.0.1
  # bloc_test: ^10.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
  generate: true

  # 资源文件
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # 字体配置
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  main_locale: zh_CN
