name: sky_eldercare_family
description: 'A comprehensive Flutter template with best practices'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 状态管理 - Riverpod
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # 路由导航 - GoRouter
  go_router: ^12.1.3

  # 网络请求 - Dio
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # 本地存储
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # UI组件和工具
  cupertino_icons: ^1.0.6
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # 工具类
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1

  # 日志和监控
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # 代码生成
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # 代码检查和格式化
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # 测试相关
  mockito: ^5.4.4
  mocktail: ^1.0.1
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
  generate: true

  # 资源文件
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # 字体配置
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  main_locale: zh_CN
